### ISSUE TITLE
Create your own IRC channel

### ISSUE THREAD

**Issue by KES777** [garu/Data-Printer#100]
Put this into your `META.json`

```
{
   "resources" : {
      "x_IRC" : "irc://irc.perl.org/#debughooks"
   },
}
```

This will create additional link at menu on metacpan: [Questions? Chat with us!](https://chat.mibbit.com/?channel=%23debughooks&server=irc.perl.org) ( I also available there)
[Demo1](https://chat.mibbit.com/?channel=%23mojo&server=irc.perl.org), [Demo2](https://metacpan.org/release/KES/Devel-DebugHooks-0.02_15)

If you do so your users will reach you simpler and vice versa =)

**Comment by garu** [comment]
Hey @KES777 I've had some issues with maintaining irc channels for modules, so I don't think Data::Printer should have its own for now. You can still ask question/open issues here, or ping me on irc even without a channel :)

Thanks!
