### ISSUE TITLE
Maybe it is time to release a new version?

### ISSUE THREAD

**Issue by bessarabov** [garu/Data-Printer#102]
The current CPAN version of Data::Dumper is 0.38. But since that several commits have appeared in master. 

The CPAN version thinks the data is a number and does not use quotes around it:

    $ perl -MDDP -E '%h = ( a => "asdf", bb => "2016-11-02"); p %h;'
    {
        a    "asdf",
        bb   2016-11-02
    }

But in master this bug is fixed:

    $ perl -Ilib -MDDP -E '%h = ( a => "asdf", bb => "2016-11-02"); p %h;'
    {
        a    "asdf",
        bb   "2016-11-02"
    }

(here is commit that fixes this c30d6f063edc972c8c35fefc8987ccde84d8beb6 ).

I have stepped several times into this pitfall. My .dataprinter ( https://gist.github.com/bessarabov/1c889f2103101b995ca3cb9abe44d614 ) shows data that can be used in perl code:

    $ perl -MDDP -E '%h = ( a => "asdf", bb => "2016-11-02"); p \%h;'
    {
        a => 'asdf',
        bb => 2016-11-02,
    }

and because there are no quotes around `2016-11-02` in perl this converted into number 2003. This error is super simple, but several times it took me some time to find out what is going on.

So, maybe you can release a new version of Data::Printer?

**Comment by garu** [comment]
Done! Sorry for taking so long :)

**Comment by bessarabov** [comment]
🎉
