### ISSUE TITLE
Bug. Data::Printer does not recognize object. 

### ISSUE THREAD

**Issue by bessarabov** [garu/Data-Printer#105]
Here is the expected behaviour:

```
$ perl -MDDP -E '$obj = {}; bless $obj, "MyObj"; p $obj;'
MyObj  {
    public methods (0)
    private methods (0)
    internals: {}
}
```
But if I use `HASH` as a CLASSNAME for the `bless`, Data::Printers starts thinking that this is not an object, but a simple hashref:

```
$ perl -MDDP -E '$obj = {}; bless $obj, "HASH"; p $obj;'
\ {}
```

Data::Dumper does not have this problem:

```
$ perl -MData::Dumper -E '$obj = {}; bless $obj, "MyObj"; warn Dumper $obj;'
$VAR1 = bless( {}, 'MyObj' );
$ perl -MData::Dumper -E '$obj = {}; bless $obj, "HASH"; warn Dumper $obj;'
$VAR1 = bless( {}, 'HASH' );
```

The same problem is with the `ARRAY` CLASSNAME:

```
$ perl -MDDP -E '$obj = []; bless $obj, "ARRAY"; p $obj;'
\ []
```

**Comment by dur-randir** [comment]
```
perl -MDDP -E '$obj = {}; bless $obj, "0"; p $obj;'
```

For more fun)

**Comment by dur-randir** [comment]
I've dug further into this. And it doesn't look pretty - there're many bugs lurking inside:

- p_without_prototypes() rejects proper references (or references them one more time, etc). This one comes from the ref() check being done on the input. This one is easy and I already have a fix for it.
- _print_and_return() dereferences it's argument guided by the ref() check. This'd definitely fail, I just can't trigger it yet, as of the following.
- _data_printer() peeks at a flat hash of both class names and built-in types, and calls whatever waits there for a given ref(). And there just happens to be a built-in ARRAY handler. Oops. And this requires much deeper changes than everything else.

**Comment by garu** [comment]
@bessarabov @dur-randir though I don't think any of us ever expect to see classes like "0" in any real world code (yes I have hope :P), I must say that was a really interesting problem to solve :)

I had to split filters internally as *class_filters* and *type_filters* and distribute all core filters accordingly. Now when you create a filter either with the `filter` exported sub or using the `key => sub { ... }` shortcut, it checks the filter name and sets it as a *class* filter unless the name is one of the expected *type* filter keywords (SCALAR, HASH, etc).

So right now setting a filter for a class named "ARRAY" or "SUB" is not supported (as the filter will be treated as a type filter). If you think we *should* support it, we can do so trivially by exporting a `class_filter` sub, which would simply put the filter under the right internal key.

Current status (github master, CPAN 0.99_006):

```
$ perl -Ilib -MDDP -E '$obj = {}; bless $obj, "MyObj"; p $obj;'
MyObj  {
    public methods (0)
    private methods (0)
    internals: {}
}
$ perl -Ilib -MDDP -E '$obj = {}; bless $obj, "HASH"; p $obj;'
HASH  {
    public methods (0)
    private methods (0)
    internals: {}
}
$ perl -Ilib -MDDP -E '$obj = []; bless $obj, "ARRAY"; p $obj;'
ARRAY  {
    public methods (0)
    private methods (0)
    internals: []
}
```

And finally, @dur-randir's special:

```
$ perl -Ilib -MDDP -E '$obj = {}; bless $obj, "0"; p $obj;'
0  {
    public methods (0)
    private methods (0)
    internals: {}
}
```
