### ISSUE TITLE
Documentation doesn't reflect return_value change

### ISSUE THREAD

**Issue by haarg** [garu/Data-Printer#108]
The default return_value was changed from `dump` to `pass`, but the documentation hasn't been fully updated to reflect that.  The "Minding the return value of p()" and "CUSTOMIZATION" sections both reflect the old default value.

**Comment by garu** [comment]
Hey @haarg! Thank you for letting us know. Commit bf40be6 adds a specific mention of all incompatible changes so far, and I've also reviewed those sections to make sure they now reflect the new value.

Thanks!
