### ISSUE TITLE
Installing fails during perldost_strawberry

### ISSUE THREAD

**Issue by Londran** [garu/Data-Printer#110]
Hello,
I tried to build my own strawberry perl as described here http://search.cpan.org/~kmx/Perl-Dist-Strawberry-4.013/script/perldist_strawberry
Install of Data::Printer fails with errorcode 6400.

Any Ideas here?

**Comment by chorny** [comment]
Did you try to build 5.25.10? In that case see https://github.com/garu/Data-Printer/pull/97  - you can just skip these tests.

**Comment by garu** [comment]
@Londran thank you for the report, and apologies for not replying sooner. Also, thanks @chorny for the help!

Are you able to reproduce this now, after the patch? I'm going to close the issue, but if you still can't install it on Strawberry, please let us know so we can reopen it. Also, any other information you may have on how to reproduce this would be greatly appreciated!

Thanks!
