### ISSUE TITLE
0.39 tag is missing from repository

### ISSUE THREAD

**Issue by karenetheridge** [garu/Data-Printer#113]
Could you please push up the latest changes and the last release tag?

**Comment by garu** [comment]
@karenetheridge [Done](https://github.com/garu/Data-Printer/releases/tag/v0.39)! Thanks for the head's up :)

**Comment by karenetheridge** [comment]
Thanks!

Now, which branch contains the v0.39 commit? it isn't on master... :)

**Comment by garu** [comment]
@karenetheridge whaa... I can see it here on github (https://github.com/garu/Data-Printer/commit/974ba874b4f1b8391203228bf4683b558f2894b0) and on my master. Did I screw up somewhere?

**Comment by karenetheridge** [comment]
The commit is there on github, but it's not in the master branch. You still need to `git checkout master; git push`.

**Comment by garu** [comment]
this is weird. I could have sworn I did that. Anyway, hopefully it's all set now :)

Thanks again!

**Comment by karenetheridge** [comment]
yes, it's all good now. :D :D :D
