### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by KES777** [garu/Data-Printer#117]
On the [page](https://metacpan.org/pod/Data::Printer)

    or change the return value to 'dump' and ask for p()'s return value instead: value:

at this position: `value instead: value:`

**Comment by garu** [comment]
Hey @KES777! I've made a bunch of updates to Data::Printer, and a documentation overhaul is in progress. I've fixed the typo but please keep an eye out for other issues either on the docs or on the code, and let me know if you bump into anything :)

Thanks!
