### ISSUE TITLE
.dataprinter is broken in master

### ISSUE THREAD

**Issue by dur-randir** [garu/Data-Printer#121]
After 8ccd48b8bdefcf608e62558c3f975652e6ba477f the following error is printer if .dataprinter file is present:

[Data::Printer] error reading rc file '/Users/dur-randir/.dataprinter': syntax error at line 1: { at blib/lib/Data/Printer/Config.pm line 67.

**Comment by garu** [comment]
@dur-randir Yes! The new version's only backwards incompatible change is the format of `.dataprinter`. However, I have just released a new commit that allows you to convert from the old format to the new one, with:

```
perl -Ilib -MData::Printer::Config -E 'Data::Printer::Config::convert( "/path/to/old/.dataprinter" )'
```

This will print the new format on screen, and show warnings when there's an error. *it will NOT change your file*, you'll have to replace it yourself by copy-pasting the output to the file.

The new file format is not documented yet, but it is simpler to maintain, way more secure and allows a very interesting new feature. It's basically a bunch of `attribute = value` lines. No quotes are required and nested attributes (like "class" or "color" get a dot (.) in it. So for example:

```perl
    class => {
        inherited => "all",
        linear_isa => 1
     }
```

becomes:

```
class.inherited = all
class.linear_isa = 1
```

The bad news is that inline filters will not work anymore on .dataprinter files. The good news is it was a security issue and we're better off without it in the long run anyway. Besides, users may just create a filter with whatever they had inline on their `.dataprinter` and continue business as usual (hopefully).

Oh, and the new feature? Now you can have custom DDP settings for each project you maintain (or, rather, for each class where you run `p()` and `np()` statements! For example:

```
multiline = 0
class.expand = 0

[MyApp::Module::Being::Debugged]
multiline = 1
class.expand = 1

[OtherApp]
show_refcount = 1
show_memsize = 1
class.show_methods = all
class.inherited = public
```

Hope you enjoy it! Oh, and let me know if you bump into any other issues!

**Comment by dur-randir** [comment]
>Oh, and let me know if you bump into any other issues!
Incoming :)
