### ISSUE TITLE
enumerate functions which are exported by DDP

### ISSUE THREAD

**Issue by KES777** [garu/Data-Printer#129]
It would be cool if DOC enumerate functions which are exported by DDP

**Comment by garu** [comment]
Hi @KES777! We do that already, don't we? DDP (currently) only exports `p()` and `np()`, and they are documented. Check out https://metacpan.org/pod/release/GARU/Data-Printer-0.99_012/lib/Data/Printer.pm

Do you think the docs could be clearer on that aspect? Let me know if there's anything we can do to make it better!

**Comment by KES777** [comment]
the latest version has that I ask. (0.40 not yet)
