### ISSUE TITLE
Converting old rc file results in an empty file

### ISSUE THREAD

**Issue by oalders** [garu/Data-Printer#134]
Given this file:

```perl
{
    end_separator => 1,
    filters =>
        { -external => [ 'DBIx::Class', 'DB', 'DateTime', 'JSON', 'URI' ], },
    hash_separator => ' => ',

    # set index => 0 when dumping a data structure you want to copy/paste into code
    index         => 1,
    scalar_quotes => q{'},
};
```

Using `our $VERSION = '0.99_020';`

```sh
$ perl -MData::Printer::Config -E 'Data::Printer::Config::convert(q(/Users/olaf/.dataprinter))' > foo.cfg
[Data::Printer]  [*] path 'filters.-external': expected scalar, found ARRAY. Filters must be in their own class now, loaded with 'filter'
 at -e line 1.
```

The biggest problem here is that if I blindly run the suggested `cp /Users/olaf/.dataprinter /Users/olaf/.dataprinter.old && perl -MData::Printer::Config -E 'Data::Printer::Config::convert(q(/Users/olaf/.dataprinter))' > /Users/olaf/.dataprinter` then I end up with an empty rc file.

**Comment by oalders** [comment]
I wonder if it would be less complicated to have a new rcfile extension moving forward and have the newest version fall back to using the older format while still issuing the warning.  In my case I've got my `.dataprinter` file in my dotfiles and I won't necessarily have the same version of `Data::Printer` available in my various projects.

Anyway, that part is not such a big deal.  I can work around that.  I had blindly run the suggested command earlier and was surprised to find (at a much later date) that the new rcfile was empty.  It's my bad for assuming it "just worked", but it's worth noting.

**Comment by garu** [comment]
@oalders ouch! Sorry! I'll fix it, and I'm glad you had a backup 😁 

The move to a new format is mostly to avoid the security risks of `eval()`'ing code from a user's home directory, so it's probably best if we don't provide a fallback to the old format. That said, I did miss the use case of different local versions of Data::Printer on the same system - one of them will not be able to read the rcfile unless the _DATAPRINTERRC_ env variable is set for that project (and only that project). I'll think about what we can do to mitigate this. The easiest is indeed to just use another name, but do you think that's a good idea and/or have any suggestions?

Thanks!

**Comment by garu** [comment]
So, 0.99_022 is out with a lot of fixes, this one included. I changed the documentation to include a `say` on that code snippet, which was the actual reason the command resulted in an empty file (fortunately the command also saves a backup!). Still, the conversion of external plugins was not working and now is:

```
$ cat /Users/garu/.dataprinter.olaf
{
    end_separator => 1,
    filters => {
        -external => [ 'DBIx::Class', 'DB', 'DateTime', 'JSON', 'URI' ],
    },
    hash_separator => ' => ',

    # set index => 0 when dumping a data structure you want to copy/paste into code
    index         => 1,
    scalar_quotes => q{'},
};

$ perl -MData::Printer::Config -E 'say Data::Printer::Config::convert(q(/Users/garu/.dataprinter.olaf))' > /Users/garu/.dataprinter.olaf.new

$ cat ~/.dataprinter.olaf.new
end_separator = 1
filters = DBIx::Class, DB, DateTime, JSON, URI
hash_separator = ' => '
index = 1
scalar_quotes = '
```
The issue of having different Data::Printer versions installed is indeed relevant, and maybe we should provide a different file. But I worry this might just make people keep using the old version. Once it's stable enough  (and it should be real soon, thank you for testing!) there should be no reason why people shouldn't upgrade. Or so I hope :D

**Comment by oalders** [comment]
Thanks, @garu!
