### ISSUE TITLE
tests fail with Mojo::JSON

### ISSUE THREAD

**Issue by karenetheridge** [garu/Data-Printer#136]
Tests fail on master (post v0.99_019):

```
t/104-filter_web.t .......... 1/21 # loaded JSON 2.97001

#   Failed test 'Mojo::JSON live booleans'
#   at t/104-filter_web.t line 414.
#          got: '{ alpha:true (read-only), bravo:false (read-only), charlie:true (read-only), delta:false (read-only) }'
#     expected: '{ alpha:true, bravo:false, charlie:true, delta:false }'
t/104-filter_web.t .......... 19/21 # Looks like you failed 1 test of 21.
t/104-filter_web.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/21 subtests 
	(less 8 skipped subtests: 12 okay)
```

I bisected the failure to this commit:

```
commit a915997e33edc8fed81204648e231c57a5577e9d
Author: Breno G. de Oliveira <garu@cpan.org>
Date:   Mon Jun 18 18:15:33 2018 -0300

    JSON parsers on new Web filter bundle
```

This is with using Mojo::JSON from Mojolicious version 7.89, with Cpanel::JSON::XS 4.04 also installed (as it optionally uses it as a backend now).

**Comment by garu** [comment]
Fixed on 11bb612 - thanks for reporting!

**Comment by karenetheridge** [comment]
Could this fix be released please?

**Comment by eserte** [comment]
> Could this fix be released please?

In the meantime, CPAN.pm users may use a distroprefs file for automatic patching (including a redirect from the stable version to the latest devel version):
https://github.com/eserte/srezic-cpan-distroprefs/blob/master/Data-Printer.yml
