### ISSUE TITLE
Use of uninitialized value $file in -e at C:/Strawberry/perl/vendor/lib/Data/Printer.pm line 1051.

### ISSUE THREAD

**Issue by duselguy** [garu/Data-Printer#139]
Hello,
according to the doc:
"You can even set this to undef or to a non-existing file to disable your RC file at will."
But:
use Data::Printer rc_file => undef;
causes the problem in the title, because the related code doesn't check undef:
sub _load_rc_file {
    my $args = shift || {};
    my $file = exists $args->{rc_file}    ? $args->{rc_file}
             : exists $ENV{DATAPRINTERRC} ? $ENV{DATAPRINTERRC}
             : File::Spec->catfile(File::HomeDir->my_home,'.dataprinter');
    return unless -e $file;
Is it possible to fix the code above to bypass the rc_file processing without this warning?
Best regards,
LP

**Comment by horgh** [comment]
I'm seeing this as well. It sounds like a reoccurrence of https://rt.cpan.org/Public/Bug/Display.html?id=103206. This is with 0.40 on Perl 5.28.2 on Linux.

**Comment by duselguy** [comment]
I'm using 0.40 and Strawberry Perl 5.30.0.1 on Windows.
Still waiting the fix ...
Thank you.

**Comment by garu** [comment]
Hello! Thank you all for using Data::Printer and for taking the time to file this issue. Also, apologies for the wait!

Version 1.0.0 has just been released to CPAN with several changes to the config file. A notable one is that now the only way to point to a custom file - or no file at all - is to put an empty string on the DATAPRINTERRC environment variable:

```bash
DATAPRINTERRC='' perl app.pl
```

If you find a bug in this procedure or if you think there should be other ways to disable rc file loading, please reply to this issue making your sugegstions - your input is really appreciated!

Thank you again :)

**Comment by duselguy** [comment]
I think that ability to bypass rc_file should be also in the code (see my 1st note above). My application doesn't use any environment variables.
If it is not possible for some reasons, then the doc should be changed (see my 1st note above).
Thank you,
LP
