### ISSUE TITLE
hash key quoting should be configurable

### ISSUE THREAD

**Issue by hertzhaft** [garu/Data-Printer#140]
Currently, hash keys are always quoted with single apostrophs (if quote_keys == 1 or 'auto').
This makes the output unusable for round trip processing if there are apostrophs in the hash keys.

It would be good to have all the quoting options Perl offers for hash keys, eg. "...", '...', q{...}, qq{...} etc. Automatic escaping of quotes or apostrophs in the hash keys is probably not a practical solution. On the other hand, the option

quote_keys => [ "q{",  "}" ] 

for a pair of opening and closing quote characters would be just an enhancement of the current functionality of the "quote_keys" option.

**Comment by garu** [comment]
Hello! Thank you for using Data::Printer and for taking the time to file this issue, I really appreciate it!

Data::Printer 1.0.0 was just released to CPAN, and one of the new features is that the `quote_keys` option honors the `scalar_quotes` one. So now this happens:

```perl
    my %x = (123 => 456);
    use DDP;
    p %x;                                           # { 123   456 }
    p %x, quote_keys => 1;                          # { "123"   456 }
    p %x, quote_keys => 1, scalar_quotes => "'";    # { '123'   456 }
```

I think it's important for consistency that all scalars be quoted equally, be them hash keys or simple values. Let me know if you know of a use case where it would be interesting to distinguish them!

Also, right now quoting with `q` or `qq` is not supported, though it is a planned feature.

Thanks again!
