### ISSUE TITLE
t/41-yaml.t started to fail (with newer YAML::Syck)

### ISSUE THREAD

**Issue by eserte** [garu/Data-Printer#142]
t/41-yaml.t has started to fail recently:
```
#   Failed test 'testing odd objects (YAML::Syck)'
#   at t/41-yaml.t line 30.
#          got: '\ {
#     sample   [
#         [0] {
#             name    "foo",
#             value   "bar"
#         }
#     ]
# }'
#     expected: '\ {
#     sample   [
#         [0] some.method  {
#             public methods (0) 
#             private methods (0)
#             internals: {
#                 name    "foo", 
#                 value   "bar"  
#             }
#         }
#     ]
# }'
# Looks like you failed 1 test of 1.
t/41-yaml.t .................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```
Sample fail report at CPAN Testers: http://www.cpantesters.org/cpan/report/87f14fe6-4718-11ea-b757-1e0fefa2931e

I guess the problem started with this change in YAML::Syck: https://metacpan.org/source/TODDR/YAML-Syck-1.32/Changes#L5

**Comment by greeneg** [comment]
Getting the same error. I'll be posting a PR shortly for a fix that can be reviewed and merged.

**Comment by greeneg** [comment]
Seems that this test is no longer available in master. Likely this will be ressolved in a later release

**Comment by eserte** [comment]
> Seems that this test is no longer available in master. Likely this will be ressolved in a later release

Yes, the development version GARU/Data-Printer-0.99_020.tar.gz does not have this test file anymore. However the development version has other problems (https://github.com/garu/Data-Printer/issues/136).

**Comment by garu** [comment]
Hello! I am pleased to announce that Data::Printer 1.0.0 has just been released on CPAN. As mentioned in this issue, it no longer contains the file so any other issues that come up are probably better addressed on their own separate issues.

Thanks again for using Data::Printer and for taking the time to open and analyze this issue!
