### ISSUE TITLE
POD "Return Value" says default is pass-through, but "CUSTOMIZATION" says it is dump

### ISSUE THREAD

**Issue by jonassmedegaard** [garu/Data-Printer#153]
Seems POD section CUSTOMIZATION has not been updated regarding default return value: It says it is `dump` but also says to look at section "Return Value" for details which says default value is `pass-through`.

**Comment by garu** [comment]
Hi Jonas! Thank you for using Data::Printer and for taking the time to file this issue.

You're right, the CPAN version still says  'dump' when it should say 'pass'. The development version (currently 0.99_026) on Github and CPAN is already fixed.

I'll leave this issue open until 1.0.0 is released! Thank you!

**Comment by jonassmedegaard** [comment]
thanks for swiftly addressing this - and for the pleasant response here :-)

**Comment by garu** [comment]
Hello! I am pleased to announce that Data::Printer 1.0.0 was just released to CPAN and (hopefully) fixes this issue in the docs. Please make sure to check them out and let me know if you spot anything dodgy so we can fix it <3

Cheers!

**Comment by jonassmedegaard** [comment]
Quoting Breno G. de Oliveira (2021-02-24 14:52:36)
> Hello! I am pleased to announce that Data::Printer 1.0.0 was just released to CPAN and (hopefully) fixes this issue in the docs. Please make sure to check them out and let me know if you spot anything dodgy so we can fix it <3

Yay!

In return, I have released Data::Printer 1.0.0 was to Debian unstable - if all goes well that means it will get included in next stable release, due in a few months.

**Comment by garu** [comment]
Wow, that's really nice - thank you!
