### ISSUE TITLE
use Data::Printer alias=>"Dumper" is not even close to a drop-in replacement for Data::Dumper

### ISSUE THREAD

**Issue by tobyink** [garu/Data-Printer#154]
All of these, which would work with Data::Dumper, fail with Data::Printer:

```
print Dumper( [] );
print Dumper( [], [] );
print Dumper( \@foo );
```

It would be awesome if Data::Printer provided a function which could be used as a drop-in replacement for `Dumper` (and I don't mean supporting all of Data::Dumper's configuration variables — just a function which accepts the same parameters and returns a string).

But in the mean time, the documentation should stop suggesting `alias=>"Dumper"` as an easy way to port from Data::Dumper to Data::Printer as it seems more likely to confuse people than help them.

**Comment by garu** [comment]
Hey Toby! Thank you for taking the time to file this issue. You're absolutely right, I think the closest we could get at this point to a Data::Dumper drop-in replacement just with the settings would be:

```perl
use DDP alias => q(Dumper), use_prototypes => 0, return_value => q(dump);
```

Using those, the only thing that fails is passing multiple parameters (`print Dumper( [], [] )` and such), and I think adding an option to support this, which would ignore the options parameter, could confuse people more than help. What if we update the docs with this info, and maybe even offering a better way to do it, which I think would be:

```perl
sub Dumper { np(@_, colored => 1) }
```

This one is indeed a drop-in replacement! 

Do you think it should be enough to update the documentation like so, or should Data::Printer actually let you export a `Dumper()` function like the one above? Or maybe do it in a new dist altogether?

Let me know what you think!

**Comment by sjn** [comment]
> Do you think it should be enough to update the documentation like so, or should Data::Printer actually let you export a Dumper() function like the one above? Or maybe do it in a new dist altogether?

I'd happily vote for both a docs update and the export option. :grin:

**Comment by tobyink** [comment]
Could maybe add another module (rather than a whole new dist) called `Data::Printer::Dumper` which exports a Data::Dumper-compatible `Dumper` function.

Could be as simple as:

```perl
package Data::Printer::Dumper;
use Exporter 'import';
sub Dumper {
  require Data::Printer;
  join "\n", map Data::Printer::np($_), @_;
}
our @EXPORT = 'Dumper'; # true value :)
```

**Comment by garu** [comment]
I've [updated the documentation](https://metacpan.org/pod/Data::Printer#Migrating-from-Data::Dumper-to-Data::Printer) on 1.0.1 so it reflects what we discussed here.

Also, I'm convinced - version 1.1.0 will include a drop-in replacement for Data::Dumper, most likely as another module, as suggested.

Thanks again!
