### ISSUE TITLE
DBIC ResultSet printing breaks with literal sql

### ISSUE THREAD

**Issue by rabbiveesh** [garu/Data-Printer#158]
on line 204 of Data::Printer::Filter::DB, you assume that the `where` attribute on a resultset is a hashref. That's not always true. If you do

    $rs->search(\[ 'literal_sql(?)' => 'with a bind param' ])

then where is an arrayref-ref.

I may be able to make a patch for this.

**Comment by garu** [comment]
Hey, @rabbiveesh! Thank you for using Data::Printer and for taking the time to send this report.

If you can send a patch for this, it would be great! Otherwise, I'll see if I can work on it later tonight or over the weekend.

Thanks again!

**Comment by rabbiveesh** [comment]
Okay, i sent a PR. lemme know if you don't like the way I did it.

Not sure if you'd want to switch the ordering of the tests, also.

**Comment by garu** [comment]
Data::Printer 1.0.4 just released with your fix. Thank you!
