### ISSUE TITLE
Old config file was killed

### ISSUE THREAD

**Issue by KES777** [garu/Data-Printer#162]
![image](https://user-images.githubusercontent.com/799021/117504955-e90a1880-af8b-11eb-8cd0-8b39a0d7606f.png)

After this `.dataprinter` becomes empty ((

**Comment by garu** [comment]
Hi @KES777! Thank you for using Data::Printer and for upgrading to the new version.

Here's what happened:

1. you created a backup file called `.dataprinter.old`
2. your command failed. As a result, unfortunately, your original `.dataprinter` file was lost and became an empty file. Fortunately you had a backup!
3. But unfortunately, you ran the original command as-is, which repeats step "1" and thus creates a backup of the (now empty) `.dataprinter` file into the `.dataprinter.old` file *again*. 😱 After the error, you should have just used the second part of the migration command (the one after "`&&`").

I'm really sorry it happened. Please feel free to submit a documentation patch to help make it clearer to other users what happened and the best way to fix it.

**Comment by KES777** [comment]
I understand what happened. It would be nice if you warn users that this may happen. 

>I'm really sorry it happened.
Do not worry about. In my case there were nothing important
