### ISSUE TITLE
Print core booleans as `true` / `false`

### ISSUE THREAD

**Issue by leonerd** [garu/Data-Printer#188]
Since Perl v5.36 we have been able to distinguish actual boolean values inside variables / data structures. These ought to be printed specially.

Currently they do not:

```
$ perl -MData::Printer -E 'say p(my $var = [2 + 2, 2 . 2, 2 == 2])'
[
    [0] 4,
    [1] 22,
    [2] 1
]
ARRAY(0x5575970754b8)
```

I would have wanted to see the output:

```
$ perl -MData::Printer -E 'say p(my $var = [2 + 2, 2 . 2, 2 == 2])'
[
    [0] 4,
    [1] 22,
    [2] true
]
ARRAY(0x5575970754b8)
```

**Comment by garu** [comment]
Thank you! DDP 1.2.0 was just pushed to CPAN with support for real booleans <3
