### ISSUE TITLE
Feature Idea: Profiles

### ISSUE THREAD

**Issue by hoelzro** [garu/Data-Printer#24]
Sometimes, I'll be using Data::Printer like this:

``` perl

use Data::Printer;
p $object;
```

...only to discover that `$object` is an inside-out object, and my output contains nothing useful.  I then modify my code to look like this:

``` perl

use Data::Printer
  filters => {
    'My::Class' => sub { p($_[0]->as_hash_ref()) },
  };
p $object;
```

Now I get useful output.  However, I have to do this everywhere I'm debugging these types of objects, which can be across several files.  I **could** put this logic into `.dataprinter`, but I'd rather keep such specifics out of my standard options.  So I propose a new feature: profiles.  My `.dataprinter` would look like this:

``` perl

{
  profiles => {
   myclass => {
    filters => {
      'My::Class' => sub { p($_[0]->as_hash_ref()) },
    }
   }
  }
}
```

and I could refer to my profile like so:

``` perl

use Data::Printer
  use_profile => 'myclass'; # could also be an array ref

p $object;
```

Thoughts?

**Comment by garu** [comment]
Hello! I am happy to announce that Data::Printer 1.0.0 has just been released to CPAN \o/

It lets you address this issue in two different ways:

1. The `.dataprinter` file (which is now an actual config file and not code, so make sure you update it accordingly) now lets you define custom sections for any class. So you could write something like this:

```perl
class.inherited = 0

[My::Class]
class.inherited = 1

[Other::Class]
show_refcount = 1
```

And it will automatically toggle each setting depending on where you call `p()`.

2. Just like you requested, you may now create a module like `Data::Printer::Profile::RHOELZ` with custom settings and dynamic filters, then load it by either putting this in your `.dataprinter` file:

```
profile = RHOELZ
```

Or loading Data::Printer with it:

```perl
use DDP profile => 'RHOELZ';
```

Or even calling it dynamically on a per-call basis:

```perl
p $some_data, profile => 'RHOELZ';
```

Thank you so much for using Data::Printer and for providing this feature request. I think it's going to help others too :)

Cheers!
