### ISSUE TITLE
filter function with inheritance

### ISSUE THREAD

**Issue by tokuhirom** [garu/Data-Printer#42]
I want to add a filter function to display Teng::Row object.
But Data::Printer::Filter checks just the named class. I guess filter function should work with child classes.

code example:

```
package Foo;
use Moo;
package Bar;
use Moo;
extends 'Foo';
package Data::Printer::Filter::Foo;
filter 'Foo' => sub { };
```

In this case, just Foo is handled by filter, Bar is not filtered. I think it makes hard to create filters in some case(e.g. Data::Printer::Filter::URI's code can make shorter).

**Comment by garu** [comment]
Good news! Version 1.0 (on github master, soon on CPAN as 0.99_002) fixes the issue by changing the behaviour of filters to:

1. class has a filter? Use it.
2. traverse entire linear ISA checking for filters (or stringification) in each parent class. You may disable this step by using `class => { parent_filters => 0 }` (defaults to 1)
3. Let all "-class" filters have a go
4. Use the generic object filter, which:
    4.1. first checks for a `_dataprinter` sub and uses it if available.
    4.2. then checks for stringification (including inherited stringification) and uses if available (disable this step with `class => { stringify => 0 }`)
    4.3. then print the standard class dump.

I hope this is a satisfactory solution. If you have any comments or concerns, now is the time - or at least until 1.0 reaches CPAN :)

**Comment by oalders** [comment]
We just ran into this issue at `$work` and using the latest trial release gave us the desired results.  So, 👍 from me~
