### ISSUE TITLE
Suggestion: support for "color themes"

### ISSUE THREAD

**Issue by creaktive** [garu/Data-Printer#43]
Maybe color definitions could be extendable objects instead of the flat _HashRefs_; that would allow easier customizations on top of other's customizations (think `Data::Printer::Theme::` namespace at CPAN). For instance, I've made the following color theme that would be interesting for many users of [Solarized](http://ethanschoonover.com/solarized) terminal emulators and would like to put it on the CPAN:

``` perl
    color           => {
        array       => 'bright_green',      # base01
        number      => 'cyan',
        string      => 'cyan',
        class       => 'yellow',
        method      => 'blue',
        undef       => 'green',
        hash        => 'cyan',
        regex       => 'red',
        code        => 'green',
        glob        => 'bright_red',        # orange
        vstring     => 'cyan',
        repeated    => 'bright_magenta',    # violet
        caller_info => 'bright_green',      # base01
        weak        => 'magenta',
        tainted     => 'bright_magenta',    # violet
        escaped     => 'red',
    }
```

**Comment by garu** [comment]
@creaktive the new Data::Printer on github master features theme support:

```perl
use DDP theme => 'Monokai'
```

The soon-to-be-released 1.0 version will include the following themes: "Classic", "Material" (default), "Monokai" and "Solarized".

Thanks again for the suggestion. Took us some time but it's finally here :D
