### ISSUE TITLE
There are open bugs in rt.cpan.org

### ISSUE THREAD

**Issue by Flimm** [garu/Data-Printer#56]
According to `META.yml`, the official bug tracker for this project is here:

https://rt.cpan.org/Dist/Display.html?Name=Data-Printer

I thought it would be helpful to create an issue pointing to that bug tracker. It would probably be a good idea to either disable issues on GitHub, or change the project's metadata, thus making rt.cpan.org display a redirecting message.

**Comment by garu** [comment]
Come to think of it, I guess I like github issues better than RT :)

I changed the default tracker to here, and will move the open tickets in RT. Thanks!

**Comment by jayallen** [comment]
Thanks garu.  I too prefer GitHub issues. +1

**Comment by garu** [comment]
Marking this issue as resolved as I've (**finally**) closed the very last open RT ticket for Data::Printer :)
