### ISSUE TITLE
CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by bk** [garu/Data-Printer#64]
I was assigned this repo for the May [CPAN Pull Request Challenge][1] and am wondering which kinds of contributions you would like to receive.

[1]: http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html

**Comment by garu** [comment]
@bk oh my! I'm so sorry I only saw this tonight :(

I'm not sure what you have been working on, but I'm pretty sure it's gonna be awesome! If you are still looking for a suggestion, I'd **love** it if you could fix these issues: http://www.cpantesters.org/distro/D/Data-Printer.html?oncpan=1&distmat=1&version=0.35_01&grade=3

Please let me know if there's anything I can do to assist you in any way. I promise I'll try to fix my email so I get notified properly of these issues. Also, please feel free to look for me on twitter (@that_garu) or irc.perl.org (garu).

Thanks for taking the time to work on Data::Printer, and thank you for your help!

**Comment by bk** [comment]
I think my PR #66 fixes most of the test failures in recent versions. Please let me know if there is something else I could help with.

**Comment by garu** [comment]
@bk thank you for the great contributions! And thank you for being so patient :)
