### ISSUE TITLE
string of a number with leading and/or trailing space is not shown as a string

### ISSUE THREAD

**Issue by y** [garu/Data-Printer#70]
If the string only consists of a number and leading and/or trailing space, it is printed without quotes and highlighted as a number, but the spaces are still printed, though easy to miss. The string should be quoted for this case. 

    $ DATAPRINTERRC= perl -MDDP -E 'p $_ for " 23 ", " 2 3 "'
    23
    " 2 3 "

*from https://rt.cpan.org/Public/Bug/Display.html?id=101902

**Comment by bessarabov** [comment]
The latest version of Data::Printer is 0.36. With this version the strings are quoted:

```
bessarabov@air:~$ DATAPRINTERRC= perl -MDDP -E 'p $_ for " 23 ", " 2 3 "'
" 23 "
" 2 3 "
bessarabov@air:~$ perl -MData::Printer -E 'say $Data::Printer::VERSION'
0.36
bessarabov@air:~$
```

**Comment by bessarabov** [comment]
Hahaha =) I just found out that this fix was implemented by me several years ago — https://github.com/garu/Data-Printer/pull/48 (I have completly forgotten that I was the author of this change =)

I think that this issue can be closed.
