### ISSUE TITLE
p() is not working with list context

### ISSUE THREAD

**Issue by Snelius30** [garu/Data-Printer#76]
Is not correct with
```
my @a=(1,2,3);
p @a[0..1]; #is not correct output with no errors
```

**Comment by dur-randir** [comment]
That's just how perl prototypes work. By default p() function has (\[@$%&]) significant part of prototype. It's meaning is "give me a reference to anything". And "give me a reference" implies scalar context. Array subscript produces list, and list in scalar context gives it's last element, ref to which you see down the road.

**Comment by jayallen** [comment]
A quick workaround fwiw:

    my @a=(1,2,3);
    p @{[@a[0..1]]}; #is not correct output with no errors

Output compared:

     $ perl -MData::Printer -E 'my @a=(1,2,3); p @a[0..1];'
    Printing in line 1 of -e:
    2
     $ perl -MData::Printer -E 'my @a=(1,2,3); p @{[@a[0..1]]};'
    Printing in line 1 of -e:
    [
        [0] 1,
        [1] 2
    ]

**Comment by dur-randir** [comment]
Or just leave prototypes behind)

**Comment by jayallen** [comment]
Sure, but I personally generally like Data::Printer's `use_prototypes` default setting.  My desire to do the above is the exception rather than the rule.

**Comment by Snelius30** [comment]
Workaround is a *brackets hell*
Actually, I d't like prototype here. But sure, author should be approve.
Anyway this is a **bug** and i think it's should be fixed. Data::Dumper is have not this problem and i trying to replace Data::Dumper to Printer for my code and this bug is so sadly.

**Comment by dur-randir** [comment]
Data::Dumper doesn't use prototypes for it's Dump() function. Data::Printer also has at least two ways to get unprototyped interface, you can check it's docs more thoroughly.

**Comment by Snelius30** [comment]
Anyway i have this
```
~$ perl -E 'use Data::Printer {use_prototypes => 0}; @a=(1,2,3); p(@a[0..1]);'
When calling p() without prototypes, please pass arguments as references at -e line 1.
```
With ref. is error too. (Odd number of elements)
btw with Dumper is still no problem. I think D::P must have the same simple interface for Dumper replacement in code. It's only my opinion of course

**Comment by dur-randir** [comment]
>With ref. is error too. (Odd number of elements)
Again, you're trying to make a reference to a list, not to an array. Consider "Making References" in perldoc perlref.

perl -E 'use Data::Printer {use_prototypes => 0}; @a=(1,2,3); p([@a[0..1]]);'
Work just fine.

**Comment by vividsnow** [comment]
@Snelius30, you maybe interested in my fork: https://github.com/vividsnow/Data-Printer which implements useful shortcuts for printing declarations (as hash or array) in list context (more info: https://github.com/garu/Data-Printer/pull/63 )

**Comment by Snelius30** [comment]
@vividsnow Ok, why not. I will test it. It's a module is present on the cpan?

**Comment by vividsnow** [comment]
@Snelius30 no

**Comment by Snelius30** [comment]
Well. I think i understand community point for this issue. It's can be closed.
