### ISSUE TITLE
Option to show overloaded stringification of objects

### ISSUE THREAD

**Issue by bpj** [garu/Data-Printer#77]
Hi,

since quite some time back I have a filter `'Path::Tiny'  => sub { "$_[0] (Path::Tiny)" }` in my `.dataprinter`, so that Path::Tiny objects are represented by their overloaded stringification. Today I discovered that I really wanted the same for Path::Class objects, but there was a snag: I had to throw in a filter each for Path::Class::File and Path::Class::Dir!
That got me thinking: next time I'll need the same for File::Temp objects too.

So I started writing a Data::Printer::Filter::Path module...

That's when I realized that objects which have an overloaded stringification have it for a reason, and that in practically all cases that stringification is the only really interesting thing about those objects from a data dumping perspective.  So why not (a) general option(s) to show objects with overloaded stringification as their stringification?  If you happen to be debugging a class with overloaded stringification you could add an overriding filter, or there could be an option `no_stringification => ['My::Class', ...]`.

What do you think?  That path filter module will probably come around sooner than later, because there are easily options which are relevant with path objects (at least absolute/relative representation and whether to actually show the path of tempfiles) but surely there is a case for the general case, no?

**Comment by dur-randir** [comment]
There're a couple of points to consider:

1) Does one want to examine class internals, it's human interpretation, or both? If this feature becomes core and not a plugin, all three options must be addressed.
2) There are at least two overloads, namely "" and 0+, that can be interpreted as an object's desirable value. At the absence of "" overload, should we look at the 0+?
3) Some modules, despite having "" overload, benefit from a custom filter. For example, look at the https://github.com/dur-randir/Data-Printer/commit/63af1041a8791dffbb6715bfd076c7f85f7ac424 proposal - default stringification of the Panda::Date is just a $_[0]->iso, without added timezone. So this feature's filter should definitely be at the end of the filters chain, so all specific class filters are run first.
4) You can try and implement this as a -class filter in a custom module by using overload::Method.

**Comment by garu** [comment]
Hey @bpj and @dur-randir! Thanks for opening the issue and sorry for the long wait.

The new Data::Printer on github master (on CPAN as 0.99_X, soon to be 1.0) has the following new features:

```perl
use DDP; p $object, class => { stringify => 1, parent_filters => 1 };
```

They behave the following way:

**stringify** - true by default, will print the stringified version of the object if one is available. It will look for string/number overloads, then for `as_string` and `stringify` methods, and use anything it finds.

**parent_filters** - true by default, will look at the entire linear ISA for filters if it can't find one for that particular class, and that includes overloads and `as_string`/`stringify` implementations.

Hope this helps!

Cheers

**Comment by bpj** [comment]
(Sorry for late reply. I've been out of office for a couple of weeks for no fun reasons.)

Many thanks for this @garu!

In the meantime I've mostly succeeded in hacking my way around the problem.
My `~/.dataprinter` has contained the following for some time

```perl
filters => +{
    'Regexp' => sub {   # Try to get reasonable output under perl 5.8!
        (   defined( $ENV{DDP_STRINGIFY_REGEX} ) # use class-specific env var if defined
            ? $ENV{DDP_STRINGIFY_REGEX}
            : $ENV{DDP_STRINGIFY} )     # otherwise check "global" env var
            or return;                  # return unless env var(s) are true
        return "$_[0] (Regex)";         # Return stringification and class/type in parens
    },
    'File::Temp' => sub { # A slight variation on the idiom
        $ENV{DDP_FILE_TEMP_GUTS} and return; # Because we return 'File::Temp' by default!
        (   defined( $ENV{DDP_STRINGIFY_FILE_TEMP} )
            ? $ENV{DDP_STRINGIFY_FILE_TEMP}
            : $ENV{DDP_STRINGIFY} )                  
          or return '(File::Temp)';     # Special default return value
        return "$_[0] (File::Temp)";
    },
    -class => sub { # Generalized version for all overloaded/stringifying classes
        require overload;
        my ( $self ) = @_;
        # Check env var DDP_STRINGIFY_This_Class
        ( my $key = 'DDP_STRINGIFY_' . ref( $self ) ) =~ s/::/_/g;
        ( defined( $ENV{$key} ) ? $ENV{$key} : $ENV{DDP_STRINGIFY} )
          or return;
        my $overloaded = !!overload::Method( $self, '""' ); # Check for string overload
        my ( $stringify )       # Check for reasonable stringification methods
          = $overloaded ? undef : grep { $self->can( $_ ) } # official overloading wins
          qw( stringify as_string to_string as_HTML to_html as_text string );
        $overloaded or $stringify or return;
        my $string = $stringify ? $self->$stringify : "$self";
        my $cols = $ENV{DDP_MAX_STR_COLS} || 70;
        if ( $string =~ /^(\X{$cols})\X/ ) { # keep at most 70/$cols text columns
            $string = qq["$1"...];
        }
        return sprintf "$string (%s)", ref $self;
    },
},
```

The `//` operator would have made this code less verbose, but I need my `.dataprinter` to work under perl 5.8 as well.

I guess I could have set all those variables in the import args instead of/as well as in env variables, but it's pretty nifty to be able to set things through env variables, especially as I mostly run debugging code from inside Vim, and can set the vars in Vim's local environment.
TBH I've mostly had DDP_STRINGIFY set to true but being able to turn it off for specific classes is pretty convenient.

Seems like I missed overloaded numification entirely! :-)
