### ISSUE TITLE
Tests are broken in master

### ISSUE THREAD

**Issue by dur-randir** [garu/Data-Printer#78]
Commit 81928a7cec37de89eb29baf9b28b1d39904b7eca broke CI tests:

```
t/26.7-unicode.t ............ 1/? Wide character in print at /home/travis/build/garu/Data-Printer/blib/lib/Data/Printer.pm line 183.
"☃" (U)
#   Failed test 'unicode scalar gets suffix'
#   at t/26.7-unicode.t line 20.
Wide character in print at /home/travis/perl5/perlbrew/perls/5.10/lib/5.10.1/Test/Builder.pm line 1826.
#          got: '☃'
#     expected: '"☃" (U)'
"�"
#   Failed test 'ascii scalar without suffix'
#   at t/26.7-unicode.t line 27.
#          got: '�'
#     expected: '"�"'
# Looks like you failed 2 tests of 4.
t/26.7-unicode.t ............ Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests 
```

**Comment by bessarabov** [comment]
Here is a link to the failing build in travis — https://travis-ci.org/garu/Data-Printer/builds/99246629

**Comment by bessarabov** [comment]
I confirm, runnig test on my computer shows the error.

**Comment by garu** [comment]
@nrdvana could you take a quick look please? :)

**Comment by nrdvana** [comment]
@garu Sure. It worked in 2014 when I wrote it ;-)

It looks like the default return value changed from "dump" to "pass".  I was using the return value to check the printed content in my testcase.  I set the config option {return_value=>"pass"} and it works again.  Pull request is in #79

**Comment by garu** [comment]
@nrdvana++

Merged and closed!
