### ISSUE TITLE
Suggestion: support for extended colors

### ISSUE THREAD

**Issue by trapd00r** [garu/Data-Printer#8]
Hi garu,

I really like this module. I am wondering if you'd consider supporting the extended colorset (color index 16 - 255). I am thinking that all this would be possible:

```
use Data::Printer {
  color => {
     array       => 'bright_white',  # ANSI, index 15
     number      => 4,               # ANSI, index 4, blue
     string      => 220,             # Extended; index 220, yellow
     string      => 'red1',          # Extended; index 196, ff0000
     class       => 'orchid',        # X11 color name
     undef       => 'sandybrown',    # X11 color name

    ...
  },
};
```

[Term::ExtendedColor](https://github.com/trapd00r/Term-ExtendedColor) can do this. Of course, it doesn't make sense to add another dependency for this (although it can replace Term::ANSIColor, but that'd need some rewriting...), but perhaps it could be added as an optional one; if the user happens to have it installed, this could be allowed.

Or do you think it'd just bring clutter to the table?

Cheers,

**Comment by garu** [comment]
Hey @trapd00r! Took us a while but the new version on github master supports extended colors in any of the following formats: 

* `color_name` (like Term::ANSIColor)
* `#rrggbb`
* `rgb(000,111,222)`

Hope this helps! Cheers!

**Comment by trapd00r** [comment]
Thanks @garu, just when I started getting back into Perl! Good job!
