### ISSUE TITLE
Data::Printer::Filter could import np()

### ISSUE THREAD

**Issue by oalders** [garu/Data-Printer#80]
Right now Data::Printer::Filter doesn't import `np()`.  I can get around this in my filter with:

```
require Data::Printer;
return Data::Printer::np( %foo );
```

That doesn't seem like it's the best way to do this, though.  :)  I can send a pull request if this is something you're open to.

**Comment by garu** [comment]
@oalders absolutely! If you make a PR, I'll merge it!
