### ISSUE TITLE
Doesn't play nicely with Hash::Objectify

### ISSUE THREAD

**Issue by oalders** [garu/Data-Printer#96]
Hi @garu.  I hope all is well.  :)

Ran across this at $work this morning.  I haven't poked around too much, but I do see that this is happening in `Hash::Objectified::AUTOLOAD`

```
use strict;
use warnings;

use Data::Printer;
use Hash::Objectify qw( objectify );

my $object = objectify({ foo => 'bar' });

p( $object );
```
```
bash-3.2$ perl objectify.pl
Can't locate object method "_data_printer" via package "Hash::Objectified0" at /Users/olaf/perl5/lib/perl5/Hash/Objectify.pm line 83.
```

**Comment by dur-randir** [comment]
% cat test.pl
use Hash::Objectify qw( objectify );

my $foo = objectify({ foo => 'bar' });
if ($foo->can('killme')) {
    $foo->killme;
}

% perl test.pl
Can't locate object method "killme" via package "Hash::Objectified0" at /Users/dur-randir/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/Hash/Objectify.pm line 84.
	Hash::Objectified::AUTOLOAD(Hash::Objectified0=HASH(0x7f980c0f1f80)) called at /Users/dur-randir/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/Hash/Objectify.pm line 67
	Hash::Objectified::can(Hash::Objectified0=HASH(0x7f980c0f1f80), "killme") called at test.pl line 4

I've changed Hash:: Objectify die() call to confess() to better show you what's happening here. It dies not inside the killme() method call, but when one tries to detect whether is it safe to call it in the first place using can(). From my point of view, that's a broken behavior on the Hash::Objectify part.

**Comment by oalders** [comment]
@dagolden, thoughts?

**Comment by dur-randir** [comment]
Better summon him as @xdg, I think)

**Comment by xdg** [comment]
Hash-Objectify-0.004 shipped to CPAN

**Comment by oalders** [comment]
Works nicely.  Thanks, @xdg! Thanks for your input @dur-randir.
