### ISSUE TITLE
Tests fail with bleadperl (scalar(%hash) changes?)

### ISSUE THREAD

**Issue by eserte** [garu/Data-Printer#98]
With perl 5.25.3 and later some tests fail like this:

```
#   Failed test 'pass-through return (hash scalar)'
#   at t/27-pass_through.t line 47.
#                   '1'
#     doesn't match '(?^:^1/\d+$)'
# Looks like you failed 1 test of 24.
t/27-pass_through.t ......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/24 subtests 
```

I did not look into the issue, but probably it's related to this change (from perl5.25.3's perldelta):

>  "scalar(%hash)" return signature changed
>    The value returned for "scalar(%hash)" will no longer show information
>    about the buckets allocated in the hash. It will simply return the count
>    of used keys. It is thus equivalent to "0+keys(%hash)".
> 
>    A form of backwards compatibility is provided via
>    "Hash::Util::bucket_ratio()" which provides the same behavior as
>    "scalar(%hash)" provided prior to Perl 5.25.

**Comment by andk** [comment]
Capture::Tiny required to reproduce. Without Capture::Tiny all the tests t/27-pass_through* are skipped.

**Comment by andk** [comment]
Bisect stops at v5.25.2-28-g8bf4c40 and so this is in the same boat as https://rt.perl.org/Ticket/Display.html?id=128482

**Comment by dur-randir** [comment]
This is already fixed as of https://github.com/garu/Data-Printer/pull/97, but seems just not to be released yet.

**Comment by jkeenan** [comment]
A new CPAN release would be highly desirable, as this distribution is depended upon by 138 other CPAN distributions (not counting second-order reverse dependencies).

See: http://deps.cpantesters.org/depended-on-by.pl?dist=Data-Printer-0.38

**Comment by bessarabov** [comment]
@jkeenan Yep, I'm also waiting for the new release =) https://github.com/garu/Data-Printer/issues/102

**Comment by garu** [comment]
Done! Sorry for taking so long :)
